can_module: PCAN
can_device: /dev/pcan2
can_baudrate: 1000
modul_ids: [1,2,3]
joint_names: [torso_lower_neck_tilt_joint, torso_pan_joint, torso_upper_neck_tilt_joint]
max_accelerations: [0.8,0.8,0.8]
frequency: 68
OperationMode: position
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.1 # rad/sec^2
max_error: 0.2 # rad
