# canopen parameter
can_module: PCAN
can_baudrate: 1000
max_accelerations: [0.8,0.8,0.8]

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.1 # rad/sec^2
max_error: 0.2 # rad
frequency: 100

joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
module_ids: [10,7,8]
devices: ["/dev/pcan0", "/dev/pcan0", "/dev/pcan0"]
