controller_list:
  - name: arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
  - name: torso_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - torso_pan_joint
      - torso_tilt_joint