controller_list:
  - name: fake_arm_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      
  - name: fake_torso_controller
    joints:
      - torso_pan_joint
      - torso_tilt_joint
