#drive
AutoInit: false
CheckJointNames: true
cycleRate: 75
numberOfMotors: 8
#can:
#[TypeCan]
#// 0 = Can Peak Dongle
#// 1 = Can Peak USB 
#// 2 = Can Card ESD
can: 1
devicePath: /dev/pcan32

#[CanCtrl]
#// network of esd card (0 or 1)
NetESD: 0 
#// Baudrate values: 
#0 = 1000 kbit/s
#1 = 500 kbit/s
#2 = 250 kbit/s
#3 = 125 kbit/s
#4 = 50 kbit/s
#5 = 20 kbit/s
#6 = 10 kbit/s
BaudrateVal: 0
GenericBufferLen: 2000

