#Parameters for left drive
control_type: velocity_control
joint_name: bl_caster_r_wheel_joint

EncIncrPerRevMot: 4096
VelMeasFrqHz: 1
GearRatio: 12.66666666
GearEfficiency: 0.7
BeltRatio: 1
Sign: 1.0
VelMaxEncIncrS: 240000
AccIncrS: 1000000
DecIncrS: 1000000
Homing: true
HomeCoupleID: 4 #couple homing with can-device (canid): 4
HomeCoupleVelRadS: 0.2
HomePos: 26771
HomeVelRadS: 0.375
HomeEvent: 9
HomeDigIn: 0x0001
HomeTimeOut: 1000
VelPModeEncIncrS: 10
CurrentContLimit: 4.4
CurrentToTorque: 1 #todo
CANId: 3

