#Parameters for left drive
control_type: velocity_control
joint_name: br_caster_joint

EncIncrPerRevMot: 10000
VelMeasFrqHz: 1
GearRatio: 25
BeltRatio: 1
Sign: -1.0
VelMaxEncIncrS: 300000
AccIncrS: 500000
DecIncrS: 500000
Homing: false
HomePos: 0
HomeVel: 10000
HomeEvent: 9
HomeDigIn: 0x0001
HomeTimeOut: 1000
VelPModeEncIncrS: 10
CurrentContLimit: 4.4
CurrentToTorque: 1 #todo
CANId: 8

