joint_names: ["torso_2_joint","torso_3_joint"]
action_name: /torso/joint_trajectory_controller/follow_joint_trajectory
service_ns: /torso/driver
default_vel: 0.4

home: [[0.0, 0.0]]
front: [[-3.14,1.57]]
back : [[3.14,-1.57]]
