# canopen parameter
can_module: PCAN
can_baudrate: 1000
max_accelerations: [0.8]
OperationMode: position

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 100

joint_names: [ur_connector_joint]
module_ids: [11]
devices: ["/dev/pcan0"]
