auto_exposure:     True
exposure_auto_max: 25000
exposure_auto_target: 40
exposure:          0.009
auto_gain:         True
gain_auto_target: 40
gain:              1
auto_whitebalance: True
frame_id: head_color_camera_r_link
stream_bytes_per_second: 54000000
auto_adjust_stream_bytes_per_second: False
trigger_mode: streaming
packet_size: 9000
