#raw3-1
##########
# common params
run_factor: 2.0
apply_ramp: false
joy_num_buttons: 12
joy_num_axes: 6
joy_num_modes: 1
light_action_name: /light/set_light

# axes
axis_vx: 1
axis_vy: 0
axis_vz: 5
axis_roll: 4
axis_pitch: 3
axis_yaw: 2

# buttons
deadman_button: 5
safety_button: 4
init_button: 9

#mode1: Base
run_button: 7

components: {
  base: {
    twist_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_safety_topic_name: '/base/collision_velocity_filter/command',
    twist_max_velocity: [0.3, 0.2, 0.3],
    twist_max_acc: [0.5, 0.5, 0.7]
  },
  torso: {
    velocity_topic_name: "/torso/joint_group_velocity_controller/command",
    joint_velocity: [0.05, 0.05],
    twist_topic_name: '/torso/twist_controller/command_twist',
    twist_max_velocity: [0.3, 0.2, 0.3, 0.3, 0.2, 0.3]
  }
}
