#cob3-2
##########
# common params
run_factor: 2.0
joy_num_buttons: 12
joy_num_axes: 6
joy_num_modes: 4
mode_switch_button: 8
light_action_name: /light/set_light

# axes
axis_vx: 1
axis_vy: 0
axis_vz: 5
axis_roll: 4
axis_pitch: 3
axis_yaw: 2

# buttons
deadman_button: 5
safety_button: 4
init_button: 9

#mode1: Base
run_button: 7

#mode2: Trajectory controller
torso_sss_default_target_button: 1
head_sss_default_target_button: 3
arm_sss_default_target_button: 2

#mode3: Velocity group controller
arm_joint1_button: 0
arm_joint2_button: 1
arm_joint3_button: 2
arm_joint4_button: 3

up_down_button: 5
right_left_button: 4

components: {
  base: {
    twist_topic_name: '/base/twist_controller/command',
    twist_max_velocity: [0.3, 0.2, 0.3],
    twist_max_acc: [0.5, 0.5, 0.7]
  },
  torso: {
    sss_default_target: "home",
    velocity_topic_name: "/torso/joint_group_velocity_controller/command",
    joint_velocity: [0.05, 0.05, 0.05, 0.05]
  },
  head: {
    sss_default_target: "front",
    velocity_topic_name: "/head/joint_group_velocity_controller/command",
    joint_velocity: [0.05]
  },
  arm: {
    sss_default_target: "home",
    velocity_topic_name: "/arm/joint_group_velocity_controller/command",
    joint_velocity: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
  }
}
