# powercube_chain parameters
can_module: PCAN
can_device: /dev/pcan1
can_baudrate: 500
modul_ids: [10]
joint_names: [tray_joint]
max_accelerations: [0.8]
min_publish_duration: 0.1
horizon: 0.1 # [s]
frequency: 68
force_use_movevel: True

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
