#cob4-6
##########
# common params
run_factor: 2.0
apply_ramp: false
joy_num_axes: 6
joy_num_modes: 1

# axes
axis_vx: 1
axis_vy: 0
axis_yaw: 3

# buttons
deadman_button: 5
safety_button: 4
init_button: 7

#mode1: Base

components: {
  base: {
    twist_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_safety_topic_name: '/base/collision_velocity_filter/command',
    twist_max_velocity: [0.3, 0.2, 0.3],
    twist_max_acc: [0.5, 0.5, 0.7]
  }
}
