defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-6/config/Elmo.dcf"
  dcf_overlay:
    "6083": "1000000"
    "6084": "1000000"
    "60C5": "1000000"
    "60C6": "1000000"

nodes:
  ##Wheel 1
  fl_caster_rotation_joint:
    id: 1
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
      "607C": "125641" # home offset
  fl_caster_r_wheel_joint:
    id: 2
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method

  ##Wheel 2
  b_caster_rotation_joint:
    id: 3
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
      "607C": "4572" # home offset
  b_caster_r_wheel_joint:
    id: 4
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method

  ##Wheel 3
  fr_caster_rotation_joint:
    id: 5
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
      "607C": "68403" # home offset
  fr_caster_r_wheel_joint:
    id: 6
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method

