devicestring: /dev/ttyUSB0
baudrate: 230400
invert_output: true
pubmarker: false
sim_enabled: false
startup_color: [0.0, 0.0, 0.0, 0.0] #rgba value
startup_mode: None #possible values: None, Static, Breath, BreathColor, Flash, FadeColor
