nodes:
  fl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-48238.5" # home offset

  b_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-167845" # home offset

  fr_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "71958.5" # home offset
