joint_limits:
  arm_left_1_joint:
    has_velocity_limits: true
    max_velocity: 0.66
    has_acceleration_limits: true
    max_acceleration: 2.635
  arm_left_2_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_left_3_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_left_4_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_left_5_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_left_6_joint:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: true
    max_acceleration: 8.727
  arm_left_7_joint:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: true
    max_acceleration: 8.727
  arm_right_1_joint:
    has_velocity_limits: true
    max_velocity: 0.66
    has_acceleration_limits: true
    max_acceleration: 2.635
  arm_right_2_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_right_3_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_right_4_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_right_5_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 4.363
  arm_right_6_joint:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: true
    max_acceleration: 8.727
  arm_right_7_joint:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: true
    max_acceleration: 8.727
  gripper_left_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
