joint_names: ['arm_right_1_joint', 'arm_right_2_joint', 'arm_right_3_joint', 'arm_right_4_joint', 'arm_right_5_joint', 'arm_right_6_joint', 'arm_right_7_joint']
action_name: /arm_right_controller/follow_joint_trajectory
service_ns: /arm_right_controller

# back side positions
home: [[2.066, -2.351, 1.407, -3.449, 1.557, 0.0, 0.0]]
zero: [[-0.54, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
