joint_names: ["sensorring_joint"]
action_name: /sensorring/joint_trajectory_controller/follow_joint_trajectory
service_ns: /sensorring/driver
default_vel: 1.0

# single positions
home: [[0.0]]
front: [[0.0]]
back: [[3.14]]
left: [[1.57]]
right: [[-1.57]]
