mode: "festival"
cepstral_voice: "David"
cepstral_settings: "\"speech/rate=170\""
fade_volume: true   #fade volume on play and on track transition
fade_duration: 0.6  #time till full volume or mute is reached
                    #(complete fade time between two tracks = 2*fade_duration)
