pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      pc1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc1
        contains: ['pc1 CPU Temperature',
                   'pc1 CPU Usage',
                   'pc1 HD Temperature',
                   'pc1 HD Usage']

      pc2:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc2
        contains: ['pc2 CPU Temperature',
                   'pc2 CPU Usage',
                   'pc2 HD Temperature',
                   'pc2 HD Usage']

  network:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Network
    analyzers:
      wifi:
        type: diagnostic_aggregator/GenericAnalyzer
        path: wifi
        num_items: 1
        expected: ['Wifi Status (ddwrt)']

  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      sound:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sound
        contains: 'sound'
        timeout: 15
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_controller'
        
## remove diagnostics from gazebo in simulated case
  simulation:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: none
    contains: 'joint'
  simulation2:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: none
    contains: 'Controller'
