## Self collision parameters for node cob_obstacle_distance

## Left: The self collision frame that shall be represented like an obstacle
## Right: The frame in the component that shall be ignored for collision checking between self collision frame an arm right component frame.
self_collision_frames: {
    head_3_link : [],
    torso_3_link : [arm_right_1_link, arm_right_2_link, arm_right_3_link, arm_right_base_link],
    base_link : [],
}

