## Cartesian controller
cartesian_controller:
  update_rate: 50.0

  # twist controller parameters
  base_link: head_base_link
  tip_link: head_center_link
  base_compensation: false
  base_active: false
  base_ratio: 0.0
  max_vel_lin: 0.5
  max_vel_rot: 0.5

  # frame_tracker + interactive_marker
  active_frame: head_center_link
  tracking_frame: head_center_target
  root_frame: odom_combined
  movable_trans: false
  movable_rot: true
  pid_trans_x: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_y: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_z: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 5.0, i: 0.0, d: 0.0, i_clamp: 0.0}

