devicedriver: ms-35
devicestring: /dev/ttyLED
baudrate: 38400
invert_output: false
pubmarker: false
marker_frame: base_link # marker will be publised at [0.5,0,0] with respect to marker_frame
startup_color: [0.0, 1.0, 0.0, 1.0] #rgba value
startup_mode: Static #possible values: None, Static, Breath, BreathColor, Flash...
