joint_names: ["torso_lower_neck_pan_joint","torso_lower_neck_tilt_joint","torso_upper_neck_pan_joint","torso_upper_neck_tilt_joint"]
home: [[0.0,0.0,0.0,0.0]]
left: [[-0.05,0.0,-0.1,0.0]]
right: [[0.05,0.0,0.1,0.0]]
front: [[0,0.1,0,0.15]]
front_extreme: [[0,0.2,0,0.25]]
front_left: [[-0.05,0.1,-0.1,0.15]]
front_left_extreme: [[-0.05,0.2,-0.1,0.25]]
front_right: [[-0.05,0.1,0.1,0.15]]
front_right_extreme: [[-0.05,0.2,0.1,0.25]]
back: [[0,-0.1,0,-0.15]]
back_extreme: [[0,-0.2,0,-0.25]]
back_left: [[-0.05,-0.1,-0.1,-0.15]]
back_left_extreme: [[-0.05,-0.2,-0.1,-0.25]]
back_right: [[0.05,-0.1,0.1,-0.15]]
back_right_extreme: [[0.05,-0.2,0.1,-0.25]]
nod: [front,home]
bow: [front_extreme, front_extreme, home]
shake: [left, right, left, home]