joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint","arm_7_joint"]

# back side positions
home: [[0.0,0.0,0.0,0.0,0.0,0.0,0.0]]
folded: [[2.429112434387207, -1.7700728178024292, 2.3842358589172363, 1.7392703294754028, 0.15917973220348358, 0.98052412271499634, 0.19730249047279358]]
pregrasp: [[2.4660451412200928, -1.6569322347640991, 1.8512247800827026, 1.3687270879745483, -1.1863553524017334, 1.0297310352325439, 0.68611335754394531]]
hold: [[2.8583388328552246, -1.6212314367294312, 2.8416802883148193, 1.9609897136688232, -0.71597582101821899, 1.7863996028900146, 1.4086482524871826]]
pre_look_at_table: [[2.6222350597381592, -1.5142182111740112, 2.4999868869781494, 1.8944116830825806, -0.40788346529006958, 1.3165892362594604, -3.4542858600616455]]
look_at_table: [[2.9914090633392334, -0.51343035697937012, 2.984553337097168, 0.73399579524993896, -0.052889171987771988, 1.0444772243499756, -3.2591197490692139]]

# front side positions
overtray: [[-1.1030212640762329, -1.1273938417434692, 2.1312966346740723, 1.2573401927947998, 0.041005752980709076, 1.3575664758682251, -0.091713562607765198]]
intermediateback: [[2.2222137451171875, -0.99453413486480713, 1.8660991191864014, 1.8985495567321777, -0.82216966152191162, 1.7891656160354614, 1.1136631965637207]]
intermediatefront: [[-0.16980814933776855, -0.43355348706245422, 1.7840240001678467, 1.8985545635223389, -0.48893314599990845, 0.84258431196212769, 0.28832489252090454]]
wavein: [[-0.1, 0.5, 0.0, 0.5, 0.0, 0.5, -1.5708]]
waveout: [[-0.1, 0.5, 0.0, -0.5, 0.0, -0.5, -1.5708]]



# trajectories
folded-to-look_at_table: [pre_look_at_table,look_at_table]
look_at_table-to-folded: [pre_look_at_table,folded]
grasp-to-tray: [intermediateback, intermediatefront, overtray]
tray-to-folded: [intermediatefront, intermediateback, folded]
wave: [waveout, wavein, waveout, wavein]
