controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - ur_connector_joint
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
  - name: torso_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - torso_lower_neck_tilt_joint
      - torso_pan_joint
      - torso_upper_neck_tilt_joint
