#Paramter for the cob_base_velocity_smoother (velocity filter for smooth navigation)

#Parameter specifying the capacity of the circular buffer (number of saved geometry messages)
circular_buffer_capacity: 12 #default value: 12

#Parameter specifying maximal time delay in seconds for saved messages (older messages will be deleted)
maximal_time_delay: 4.0 #default value: 4.0

#Parameter specifying the threshold for the maximal allowed acceleration in meters per second
thresh_max_acc: 0.3 #default value: 0.3
