auto_white_balance:    2
auto_brightness:       2
auto_exposure:         2
auto_gain:             2
auto_gamma:            2
auto_hue:              2
auto_iris:             2
# auto_saturation:     2
auto_shutter:          2
guid:                  000a470110073080
video_mode:            format7_mode0
# video_mode:          640x480_rgb8
# video_mode:          1280x960_rgb8
format7_color_coding:  rgb8
reset_on_open:         true
#iso_speed:             400
# frame_rate           15
# frame_rate           5
frame_id:              /head_color_camera_l_link
