joint_names: ["gripper_left_proximal", "gripper_left_distal"]
action_name: /gripper_left/joint_trajectory_controller/follow_joint_trajectory
service_ns: /gripper_left/driver

# single positions
home: [[-0.6, -0.4]]
close: [[-0.85, 0.1]]
open: [[0.85, -1.4]]
