joint_names: ["head_1_joint","head_2_joint","head_3_joint"]
action_name: /head/joint_trajectory_controller/follow_joint_trajectory
service_ns: /head/driver
default_vel: 0.4

home: [[0.0,0.0,0.0]]

front: [[0.0,0.0,0.0]]
front_twisted: [[-1.57, 3.14, 1.57]]
front_down: [[-1.57,3.14,-1.57]]

back: [[0.0, 0.0, 3.14]]
back_twisted: [[1.57,-3.14,1.57]]
back_down: [[1.57, -3.14, 4.7]]

left: [[1.57, 0.0, 0.0]]
right: [[-1.57, 0.0, 0.0]]

nod: [front_down,front]
shake: [left, right, left, home]
