joint_names: ["head_1_joint","head_2_joint","head_3_joint"]
home: [[0.0,0.0,0.0]]
left: [[0.0,-1.0,0.0]]
right: [[0.0,1.0,0.0]]
front: [[-1.57,0.0,0.0]]
front_extreme: [[-3.14,0.0,0.0]]
front_left: [[-1.57,-1.0,0.0]]
front_left_extreme: [[-3.14,-1.0,0.0]]
front_right: [[-1.57,1.0,0.0]]
front_right_extreme: [[-3.14,1.0,0.0]]
back: [[1.57,0.0,0.0]]
back_extreme: [[3.14,0.0,0.0]]
back_left: [[1.57,-1.0,0.0]]
back_left_extreme: [[3.14,-1.0,0.0]]
back_right: [[1.57,1.0,0.0]]
back_right_extreme: [[3.14,1.0,0.0]]
nod: [front,home]
bow: [front_extreme, front_extreme, home]
shake: [left, right, left, home]
