joint_names: ["torso_1_joint","torso_2_joint","torso_3_joint"]

home: [[0.0, 0.0, 0.0]]

front: [[0.0, 0.0, 0.0]]
front_down: [[1.57, -3.14, 1.57]]
front_down_twisted: [[1.57, 3.14, -1.57]]

back: [[3.14, 0.0, 0.0]]
back_down: [[4.7, -3.14, 1.57]]
back_down_twisted: [[-1.57, 3.14, -1.57]]

left: [[1.57, 0.0, 0.0]]
left_down_twisted: [[-3.14, 3.14, -1.57]]
left_down: [[3.14, -3.14, 1.57]]
right: [[-1.57, 0.0, 0.0]]
right_down_twisted: [[0.0, 3.14, -1.57]]
right_down: [[0.0, -3.14, 1.57]]

nod: [front_down,front]
shake: [left, right, left, home]
