stomp/arm:
  group_name: arm
  optimization:
    num_timesteps: 20
    num_iterations: 50
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.3, 1.0, 0.5, 0.4, 0.3, 0.3]
    cost_functions:
      - class: stomp_moveit/ObstacleDistanceGradient
        max_distance: 0.2
        cost_weight: 1.0
        longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [191, 0, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
stomp/robot:
  group_name: robot
  optimization:
    num_timesteps: 20
    num_iterations: 50
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.5,0.3, 1.0, 0.5, 0.4, 0.3, 0.3]
    cost_functions:
      - class: stomp_moveit/ObstacleDistanceGradient
        max_distance: 0.2
        cost_weight: 1.0
        longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [191, 0, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
