stations:
- frame_id: station_charger
  reflector_distance: 0.28
  approach_poses: [[-0.76, 0.0, 0.0], [-0.56, 0.0, 0.0], [-0.46, 0.0, 0.0]] # in frame_id coords
  departure_poses: [[-0.8, 0.0, 0.0]]
  stop_condition:
    topic: '/power_state'
    message_field: 'charging'
    compare_value: True

- frame_id: station_travel_box
  reflector_distance: 0.95
  approach_poses: [[-2.20, 0.0, 0.0], [-0.6, 0.01, -0.035], [-0.38, 0.01, -0.035], [-0.312, 0.01, -0.035]] # in frame_id coords
  departure_poses: [[-0.38, 0.01, -0.035], [-0.6, 0.01, -0.035], [-2.20, 0.0, 0.0]] # in frame_id coords

distance_tolerance: 0.05
intensity_lower_threshold: 200
intensity_upper_threshold: 10000
update_rate: 0.25
