joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    arm_left_1_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  required_drive_mode: 1

arm_left_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_1_joint
  required_drive_mode: 1
  
arm_left_1_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_left_1_joint
  required_drive_mode: 2

arm_left_2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_2_joint
  required_drive_mode: 1
    
arm_left_3_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_3_joint
  required_drive_mode: 1
  
arm_left_4_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_4_joint
  required_drive_mode: 1
  
arm_left_5_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_5_joint
  required_drive_mode: 1
  
arm_left_6_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_6_joint
  required_drive_mode: 1
  
arm_left_7_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_left_7_joint
  required_drive_mode: 1
