name: arm_right_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-2/config/Schunk_0_63.dcf"

modules:
  - name: arm_right_1_joint
    id: 51
  - name: arm_right_2_joint
    id: 52
  - name: arm_right_3_joint
    id: 53
  - name: arm_right_4_joint
    id: 54
  - name: arm_right_5_joint
    id: 55
  - name: arm_right_6_joint
    id: 56
  - name: arm_right_7_joint
    id: 57
