threshold_warning: 20 # % of battery level
threshold_error: 10 # % of battery level
threshold_critical: 5 # % of battery level

threshold_voltage_warn: 43 # voltage of battery level
threshold_voltage_error: 41.0 # voltage of battery level
threshold_voltage_critical: 40 # voltage of battery level
threshold_voltage_mid: 48 # voltage of battery level
threshold_voltage_full: 51.2 # voltage of battery level

steady_current: 5  # amperes while no axis is moving

enable_light: false
num_leds: 58
light_components: ['light_torso']

enable_sound: false
sound_components: ['sound']
