pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      b1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: b1
        contains: '-b1'
      t1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: t1
        contains: '-t1'
      t2:
        type: diagnostic_aggregator/GenericAnalyzer
        path: t2
        contains: '-t2'
      t3:
        type: diagnostic_aggregator/GenericAnalyzer
        path: t3
        contains: '-t3'
#      s1:
#        type: diagnostic_aggregator/GenericAnalyzer
#        path: s1
#        contains: '-s1'
      h1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: h1
        contains: '-h1'
#  network:
#    type: diagnostic_aggregator/AnalyzerGroup
#    path: Network
#    analyzers:
#      wifi:
#        type: diagnostic_aggregator/GenericAnalyzer
#        path: wifi
#        num_items: 1
#        expected: ['Wifi Status (ddwrt)']
 
  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'
      sound:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sound
        contains: 'sound'
      light:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Light
        contains: 'light'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      laser_top:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Right
        contains: 'laser_right'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Left
        contains: 'laser_left'

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      torso:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Torso
        contains: 'torso'
      sensorring:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sensorring
        contains: 'sensorring'
      arm_right:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Arm Right
        contains: 'arm_right'
      arm_left:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Arm Left
        contains: 'arm_left'
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_controller'

  safety:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Safety
    contains: 'safety'

## remove diagnostics from gazebo in simulated case
  simulation:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: none
    contains: 'joint'
  simulation2:
    type: diagnostic_aggregator/DiscardAnalyzer
    path: none
    contains: 'Controller'
