host: 10.4.2.99
port: "9100" # alternative syntax: !!str 9100
threshold_linear_slow: 0.1
threshold_linear_fast: 0.4
threshold_angular_fast: 0.5
marker_type: 11 # http://www.ros.org/wiki/rviz/DisplayTypes/Marker, not all are supported
scale_x: 1.0
scale_y: 1.0
scale_z: 1.0
