joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - sensorring_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    sensorring_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - sensorring_joint
  required_drive_mode: 1

sensorring_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: sensorring_joint
  required_drive_mode: 1
  
sensorring_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: sensorring_joint
  required_drive_mode: 2
