name: sensorring_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-2/config/Elmo.dcf"

nodes:
  - name: sensorring_joint
    id: 73
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6098": "35" #  homing method

