sync:
  interval_ms: 10
  overflow: 0
heartbeat:
  rate: 20
  msg: "77f#05"

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "common/Elmo.dcf"

nodes:
  - name: sensorring_joint
    id: 73
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6098": "35" #  homing method

