## Cartesian controller parameters
chain_base_link: torso_base_link
chain_tip_link: torso_center_link
root_frame: odom_combined

# twist controller parameters
twist_controller:
  hardware_interface_type: 0    #Velocity 0, Position 1, JointStates 2

  # damping parameters
  numerical_filtering: false
  damping_method: 2    #NO 0, CONSTANT 1, MANIPULABILITY 2, LeastSingularValue 3
  damping_factor: 0.01
  lambda_max: 0.1
  w_threshold: 0.005
  beta: 0.005
  eps_damping: 0.003
  eps_truncation: 0.001

  # constraints
  solver: 1    #WLN
  priority: 500    #Prio for main task
  mu: -2.0
  k_H: 1.0    #Self-motion factor for GPM

  # JLA
  constraint_jla: 1    #OFF 0, ENABLED 1, MID 1, INEQ 2
  priority_jla: 50
  k_H_jla: -10.0
  activation_threshold_jla: 10.0    #in [%]
  damping_jla: 0.000001

  # CA
  constraint_ca: 0    #OFF 0, ENABLED 1
  priority_ca: 100
  k_H_ca: -20.0
  activation_threshold_ca: 0.1    #in [m]
  damping_ca: 0.000001

  # limit enforcing
  keep_direction: true
  enforce_vel_limits: true
  enforce_pos_limits: true
  tolerance: 5.0

  # kinematic extensions
  base_compensation: false
  kinematic_extension: 0    #OFF 0, BaseActive 1
  base_ratio: 0.05
  max_vel_lin_base: 0.5
  max_vel_rot_base: 0.5

  # collision avoidance frames for obstacle distance
  collision_check_frames: [torso_3_link]

# frame_tracker + interactive_marker
frame_tracker:
  update_rate: 50.0
  tracking_frame: torso_center_target
  movable_trans: false
  movable_rot: true
  pid_trans_x: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_y: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_z: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_x: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_y: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_z: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  # abortion criteria - cfg
  cart_min_dist_threshold_lin: 0.01
  cart_min_dist_threshold_rot: 0.01
  twist_dead_threshold_lin: 0.05
  twist_dead_threshold_rot: 0.05
  twist_deviation_threshold_lin: 0.5
  twist_deviation_threshold_rot: 0.5
