host: 141.3.80.116
angle_resolution: 0.25 #deg
scan_frequency: 25 #hz
inverted: true
frame_id: base_laser_front_link
scan_intervals: [[-2.0, 2.0]] #[rad] these intervals are included to the scan
set_config: false
