controller_list:
  - name: arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: sdh_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - sdh_knuckle_joint
      - sdh_thumb_2_joint
      - sdh_thumb_3_joint
      - sdh_finger_12_joint
      - sdh_finger_13_joint
      - sdh_finger_22_joint
      - sdh_finger_23_joint
  - name: torso_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - torso_lower_neck_pan_joint
      - torso_lower_neck_tilt_joint
      - torso_upper_neck_pan_joint
      - torso_upper_neck_tilt_joint