joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint","arm_7_joint"]
action_name: /arm/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm/driver
default_vel: 0.2

# back side positions
home: [[0.0,0.0,0.0,0.0,0.0,0.0,0.0]]
folded: [[1.3727014566935403, -1.7699907543250095, -2.3800007811895476, 1.7300052611618193, -0.15999433253032017, 0.9699841850883687, -0.18997908907958275]]
pregrasp: [[1.4359347354932948, -1.6599826515718068, -1.8499966472364298, 1.369978743060429, 1.186195572825426, 1.0349976997251573, 0.8819846842028144]]

