pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: AnalyzerGroup
    path: Computers
    analyzers:
      pc1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc1
        contains: 'pc1'
      pc2:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc2
        contains: 'pc2'
      pc3:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc3
        contains: 'pc3'

#  network:
#    type: AnalyzerGroup
#    path: Network
#    analyzers:
#      wifi:
#        type: diagnostic_aggregator/GenericAnalyzer
#        path: wifi
#        num_items: 1
#        expected: ['Wifi Status (ddwrt)']
 

#  computers:
#     type: diagnostic_aggregator/AnalyzerGroup
#     path: Computers
#     analyzers:
#      cpu:
#         type: diagnostic_aggregator/GenericAnalyzer
#         path: CPU
#         expected: ['pc1 CPU Usage',
#                    'pc1 HD Usage',
#                    'pc2 CPU Usage',
#                    'pc2 HD Usage',
#                    'pc3 CPU Usage',
#                    'pc3 HD Usage']
    #   clocks:
    #     type: diagnostic_aggregator/GenericAnalyzer
    #     path: Clocks
    #     expected: ['NTP offset from pc1 to pc1',
    #                'NTP offset from pc2 to pc1',
    #                'NTP offset from pc3 to pc1',
    #                'NTP self-offset for pc1',
    #                'NTP self-offset for pc2',
    #                'NTP self-offset for pc3']
    #   network:
    #     type: diagnostic_aggregator/GenericAnalyzer
    #     path: Network
    #     num_items: 1
    #     expected: ['Wifi Status (ddwrt)']
    #     #num_items: 5
    #     #find_and_remove_prefix: 'multi_interface_roam: '

  # devices:
  #   type: diagnostic_aggregator/AnalyzerGroup
  #   path: Devices
  #   analyzers:
  #     joystick:
  #       type: diagnostic_aggregator/GenericAnalyzer
  #       path: Joystick
  #       expected: 'joy_node: Joystick Driver Status'

  # power:
  #   type: diagnostic_aggregator/GenericAnalyzer
  #   path: 'Power System'
  #   startswith: 'battery'

  io:
    type: AnalyzerGroup
    path: IO
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sound
        contains: 'sound'
        timeout: 15

  sensors:
    type: AnalyzerGroup
    path: Sensors
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'

  motors:
    type: AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_controller'
