#raw3-4
##########
# common params
run_factor: 2.0
joy_num_buttons: 12
joy_num_axes: 6
joy_num_modes: 1

# axes
axis_vx: 1
axis_vy: 0
axis_vz: 5
axis_roll: 4
axis_pitch: 3
axis_yaw: 2

# buttons
deadman_button: 5
safety_button: 4
init_button: 9

#mode1: Base
run_button: 7

components: {
  base: {
    twist_topic_name: '/base/twist_controller/command',
    twist_max_velocity: [0.3, 0.2, 0.3],
    twist_max_acc: [0.5, 0.5, 0.7]
  }
}
